quarkus.log.json=true
quarkus.log.level=INFO
quarkus.log.category."br.com.seudominio.pedidos".level=DEBUG
#quarkus.otel.exporter.otlp.endpoint=http://jaeger:4317
quarkus.micrometer.export.prometheus.enabled=true
quarkus.arc.context-propagation.mdc=true

# ??? Observability Dev Service ????????????????????????????????????????????????
# Habilita o LGTM stack automático em dev/test (requer Docker rodando)
%dev.quarkus.observability.enabled=true
%dev.quarkus.observability.dev-resources=true
%dev.quarkus.otel.sdk.disabled=true